#source 'https://git.oschina.net/yushengjie/ysj.git'
source 'http://git.ops.com/XGN-IOS/xgn.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
target 'YSJSwiftLibrary' do
    use_frameworks!
#pod 'AlertHud', '~> 1.1.0'
pod 'MediaPicker', '~> 1.3.0'
#pod 'Kvstore', '~> 1.0.1'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'AFNetworking', '~> 3.1'
pod 'Reachability', '~> 3.1.1'
#pod 'SDWebImage', '~> 3.8'
pod 'MJRefresh', '~> 3.1.15'
pod 'FMDB', '~> 2.7.2'
#pod 'FSCalendar', '~> 2.6'
#pod 'ViewDeck', '~> 2.4'
#pod 'UMengSocialCOM', '~> 5.2.1'
#pod 'SAMKeychain', '~> 1.5'
#pod 'CryptoSwift', '~> 0.6.7'
#pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'SnapKit', '~> 4.0.0'
pod 'HandyJSON', '= 4.0.0-beta.1'
pod 'Alamofire', '~> 4.5.1’
end
